version: '3'
services:
    screeps:
        image: screepers/screeps-launcher
        volumes:
            - ./config.yml:/screeps/config.yml
            - ./bots:/screeps/bots
            - screeps-data:/screeps
            - ./logs:/screeps/logs
        ports:
            - 21025:21025/tcp
            - 21026:21026
        environment:
            MONGO_HOST: mongo
            REDIS_HOST: redis
        restart: unless-stopped
        logging:
               driver: "json-file"
    mongo:
        image: mongo
        volumes:
        - mongo-data:/data/db
        restart: unless-stopped
        logging:
            driver: "local"
    redis:
        image: redis
        volumes:
        - redis-data:/data
        restart: unless-stopped
        logging:
            driver: "local"
volumes:
    screeps-data:
    redis-data:
    mongo-data: